version: "3"

services:
  mchview:
    depends_on:
      - mch-mapping-api
    image: mrrtf/mchview
    environment:
      - MCHVIEW_PORT=${MCHVIEW_PORT}
    ports:
      - "${MCHVIEW_PORT}:80"

  mch-mapping-api:
    image: mrrtf/mch-mapping-api
    environment:
      - MCH_MAPPING_API_PORT=${MCH_MAPPING_API_PORT}
    ports:
      - "${MCH_MAPPING_API_PORT}:${MCH_MAPPING_API_PORT}"

  # ccdb-api:
  #   build: 
  #     context: ./ccdb-api
  #   volumes:
  #     - /Users/laurent/alice/ccdb/local-repo:/ccdb/data
  #   environment:
  #     - TOMCAT_PORT=${CCDB_API_PORT}
  #   ports:
  #     - ${CCDB_API_PORT}:${CCDB_API_PORT}
  #
  # ccdb-json-api:
  #   # build: ./ccdb-json-api
  #   image: serve-ocdb:latest
  #   entrypoint:
  #     - /serve-ocdb
  #   command:
  #     - --ccdb
  #     - http://ccdb-api:${CCDB_API_PORT}
  #     - --port
  #     - ${CCDB_JSON_API_PORT}
  #   depends_on:
  #     - ccdb-api
  #   ports:
  #     - ${CCDB_JSON_API_PORT}:${CCDB_JSON_API_PORT}
  #
